import type { Metadata } from "next";
import ServicesLayout from "../../../lib/components/layout/services";
import AppProvider from '../../../lib/context/AppProvider';
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AppProvider>
          <ServicesLayout>
            {children}
          </ServicesLayout>
        </AppProvider>
      </body>
    </html>
  );
}
